### PR TITLE
Fix diagnose

### PR DESCRIPTION
**Pull request by SteveMattar**
Debug issue: https://github.com/submariner-io/shipyard/issues/607

### CODE REVIEW

**Comment by dfarrell07** [comment]
```
2021-07-22T14:08:57.9131887Z [36m[submariner-operator]$ [cluster2] timeout 6m bash -c deploy_weave_cni[0m
2021-07-22T14:08:57.9132641Z [cluster2] Applying weave network...
2021-07-22T14:08:57.9134150Z [cluster2] error: unable to read URL "https://cloud.weave.works/k8s/net?k8s-version=v&env.IPALLOC_RANGE=", server reported 400 Bad Request, status code=400
```

Seems like some variables aren't getting set here?

**Comment by SteveMattar** [comment]
> Seems like some variables aren't getting set here?

yeah I just made some changes in my shipyard image
forgot to export the variables

**Comment by dfarrell07** [comment]
It seems like it's not hanging at the `docker inspect` line here:

```
2021-07-22T14:30:35.8945499Z [36m[submariner-operator]$ [cluster1] kind_fixup_config[0m
2021-07-22T14:30:35.8946280Z [36m[submariner-operator]$ [cluster1] kind_fixup_config[0m
2021-07-22T14:30:35.8947609Z [36m[submariner-operator]$ [cluster1] docker inspect -f {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} cluster1-control-plane[0m
2021-07-22T14:30:35.8948502Z [cluster1] master_ip=172.18.0.7
```

Are the other commits here intentional? If not, it would be interesting to update the branches such that your debug commit is the only one in the PR.

**Comment by SteveMattar** [comment]
I used the same PR that was pushed by @sridhargaddam yesterday `gh pr checkout 1507`.
I can try to start from scratch.
The problem is starts here
```
kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=v1.20.2&env.IPALLOC_RANGE=10.1.0.0/16
```
specifically during the deployment of the `weave-net` daemonset

**Comment by SteveMattar** [comment]
@dfarrell07 I update the kind version to support k8s 1.20

**Comment by SteveMattar** [comment]
Done testing

**Pull request closed without merging**
